name: Build & Release

on:
  push:
    branches:
      - gatsby
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'

env:
  CI: true
  GATSBY_TELEMETRY_DISABLED: true

jobs:
  build-and-release:
    name: Build & Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - id: node-cache
        uses: actions/cache@v1
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - run: npm run build
        env:
          GATSBY_DISQUS_NAME: ${{ secrets.GATSBY_DISQUS_NAME }}
          GATSBY_DRAFT_PATH: draft0

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GH_PAGES_DEPLOY_KEY }}"
      - run: git remote rename origin Ailrun
      - run: git remote set-url Ailrun "git@github.com:Ailrun/Ailrun.github.io"
      - run: git config --local user.name "Junyoung Clare Jang"
      - run: git config --local user.email "jjc9310@gmail.com"
      - run: npm run release
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
